import Foundation

/// The scream shown while the pointer is on the cancel cross: angry brows, open mouth and
/// shout rays on both sides, on the same grid as the other faces.
extension PixelArt {
    static let hoverScream: [String] = [
        ".......................................",
        ".......................................",
        ".......................................",
        ".......................................",
        ".......................................",
        "...........wwwwwwwwwwwww...............",
        ".........wwwkkkkkkkkkkkwwwwwwww........",
        "........wwkkkkkkkkkkkkkkkkkkkkwww......",
        "......wwwkkkkwwwwwwwwwkkkkkkkkkkww.....",
        ".....wwkkkkwwwkkkkkkkkkkkkkkkkkkkww....",
        "....wwkkkwwwkkkkkkkkkkkkkkkkkkkkkkww...",
        "...wwkkkwwkkkkkkkkkkkkkkkkkkkkkkkkkww..",
        "...wkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkw..",
        "...wkkkkkkkkkkkkkkkkkkkkkkkwwwkkkkkkw..",
        "...wwkkkkkkkkkkkkkkkkkkkkkkwkwkkkkkkw..",
        "....wkkkkkkkkkkkkkkkkkkkkkkwwwkkkkkww..",
        ".....wkkkkkkkkkkkkkkkkkkkkkkkkkkkkkw...",
        ".....wkkkkkkkkkkkkkkkkkkkkkkkkkkkkww...",
        ".....wwkkkkkkkkwwwwwwwwwwwwwwwwwwkwww..",
        "....wwkkkkkkkkkwwkkkwwwwwkwwwwwwkkkkw..",
        "....wkkkkkkkkkkwwwkkkkwwwwkwwwwkkkkkww.",
        "....wkkkkkkkkkwwwwwwkkkkkwwkwkkkwwkkkw.",
        "...wwkkkkkkkkkwwwwwwwwkkkkkkkkkwwkkkkw.",
        "...wkkkkkkkkkkwwwkkkkkkkkkkwkkkkkkkkww.",
        "..wwkkwwwkkkkkwwwwwwkkwwwwwwkwkkwwkkw..",
        "..wkkwwwwwwkkkwwwwwwkkwwwwwwwwkkwwkww..",
        "..wkkwkkkwwkkkwwwwwwwwwwwwwwwkwwwwkww..",
        "..wkkwwkkwwwwwwwwwwwkkkkwwwwwwkkwkkwww.",
        "..wkkwwkkwwwwwwwwwwwwwwwwwwwwwwkwwkkww.",
        "..wkkkwkkwwwwwwwwwwwwwwwwkkkkkkkwwwkkw.",
        "..wwkkwwkwwwwwwwwwwwwwwkkkkkkkkwwwwkkw.",
        "...wkkwwwwkkwwwwwwwwwwkkkkkkkkkkkwwkkw.",
        "...wwkkkkkkkwwwwwwwwwkkkkkkkkkkkkkwkkw.",
        "....wwkkkkkkwwwwwwwwkkkkkwwwwwkkkkwkkw.",
        ".....wwkkkwwwwwwwwwwkkkwwwkkkwwwkkwkkw.",
        "......wkkkwwwwwwwwwwkkwwwkkkkkwwwkkkkw.",
        "......wwkkwwwkwwwwwwwwwwwkkkkkwwwwkkww.",
        ".......wwkwwwkwwwwwwwwwwwkkkkkwwwkkkw..",
        "........wkkwwkkwwwwwwwwwwkkkkkwwkkkww..",
        "........wwkkwwkkwwwwwwwwwwkkkwwwkkkw...",
        ".........wwkkkkkkkwwwwwwwwwwwwwwkkww...",
        "..........wwkkkkkkkkkwwwwwwwwwkkkww....",
        "...........wwwwwkkkkkkkkkkkkkkkkww.....",
        "...............wwwwkkkkkkkkkkkkww......",
        "..................wwwwwwwwwwwwww.......",

    ]

    static let screamOrigin = (x: -8, y: 20)
    static let screamLines: [String] = [
        "wwww................................................wwww",
        "wkkwww............................................wwwkkw",
        "wkkkkwww........................................wwwkkkkw",
        "wwwkkkkw........................................wkkkkwww",
        "..wwwkkw........................................wkkwww..",
        "....wwww........................................wwww....",
        "........................................................",
        "wwwwwwww........................................wwwwwwww",
        "wkkkkkkw........................................wkkkkkkw",
        "wkkkkkkw........................................wkkkkkkw",
        "wwwwwwww........................................wwwwwwww",
        "........................................................",
        "....wwww........................................wwww....",
        "..wwwkkw........................................wkkwww..",
        "wwwkkkkw........................................wkkkkwww",
        "wkkkkwww........................................wwwkkkkw",
        "wkkwww............................................wwwkkw",
        "wwww................................................wwww",
    ]
}
